// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';
import type { CodecTypes as ZodJsonTypes } from 'prisma-next-zod-json/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:e6997fa5a303cce743e5a69c4c91c470e6e0136e92c51a0531e9c7cae0fa958f'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:2941a843291e48205b3357532067798e0160e8604d98f4ceab93d2ebc862bdf5'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes & ZodJsonTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Account: {
      readonly id: Char<36>;
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly settings: {
        theme: 'light' | 'dark';
        locale: string;
        notifications: { email: boolean; digestHour?: number };
        tags: Array<string>;
      };
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Account: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly settings: CodecTypes['zod/json@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Account: {
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: Char<36>;
      readonly settings: {
        theme: 'light' | 'dark';
        locale: string;
        notifications: { email: boolean; digestHour?: number };
        tags: Array<string>;
      };
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Account: {
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly settings: CodecTypes['zod/json@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Account: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly settings: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'zod/json@1';
                  readonly nullable: false;
                  readonly typeParams: {
                    readonly version: 1;
                    readonly jsonSchema: '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"theme":{"type":"string","enum":["light","dark"]},"locale":{"type":"string","minLength":2},"notifications":{"type":"object","properties":{"email":{"type":"boolean"},"digestHour":{"type":"integer","minimum":0,"maximum":23}},"required":["email"],"additionalProperties":false},"tags":{"maxItems":5,"type":"array","items":{"type":"string"}}},"required":["theme","locale","notifications","tags"],"additionalProperties":false}';
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Account: { readonly namespace: 'public' & NamespaceId; readonly model: 'Account' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Account: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly settings: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'zod/json@1';
                  readonly typeParams: {
                    readonly version: 1;
                    readonly jsonSchema: '{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"theme":{"type":"string","enum":["light","dark"]},"locale":{"type":"string","minLength":2},"notifications":{"type":"object","properties":{"email":{"type":"boolean"},"digestHour":{"type":"integer","minimum":0,"maximum":23}},"required":["email"],"additionalProperties":false},"tags":{"maxItems":5,"type":"array","items":{"type":"string"}}},"required":["theme","locale","notifications","tags"],"additionalProperties":false}';
                  };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Account';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly email: { readonly column: 'email' };
                readonly settings: { readonly column: 'settings' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {
    readonly 'zod-json': {
      readonly capabilities: {};
      readonly familyId: 'sql';
      readonly id: 'zod-json';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'ZodJsonTypes';
            readonly named: 'CodecTypes';
            readonly package: 'prisma-next-zod-json/codec-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'jsonb';
            readonly targetId: 'postgres';
            readonly typeId: 'zod/json@1';
          },
        ];
      };
      readonly version: '0.1.0';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Account';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
